# -*- coding: utf-8 -*-
"""proyecto2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQva1QxZnsMShjhtS7pSJWi10UrpZAih
"""

import pandas as pd

df = pd.read_csv('ECOVSCOVID.csv')

# Informacion basica
print(df.info())
print(df.head())
print(df['COUNTRY'].unique())

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Cargar datos
df = pd.read_csv('ECOVSCOVID.csv')

# Limpieza de datos
# Rellenar nulos de HDI con el promedio
hdi_prom = df['HDI'].mean()
df['HDI'] = df['HDI'].fillna(hdi_prom)

# Convertir fecha
df['DATE'] = pd.to_datetime(df['DATE'])

# Filtrar datos de Mexico
mex = df[df['COUNTRY'] == 'Mexico']

# Datos globales promedio por fecha
global_prom = df.groupby('DATE')[['TC', 'TD', 'STI']].mean().reset_index()

# Grafica 1: Casos Totales (TC)
plt.figure(figsize=(10, 6))
plt.plot(mex['DATE'], mex['TC'], label='Mexico')
plt.plot(global_prom['DATE'], global_prom['TC'], label='Promedio Global', linestyle='--')
plt.xlabel('Fecha')
plt.ylabel('Casos Totales (Log)')
plt.title('Comparacion de Casos Totales: Mexico vs Global')
plt.legend()
plt.grid(True)


# Grafica 2: Muertes Totales (TD)
plt.figure(figsize=(10, 6))
plt.plot(mex['DATE'], mex['TD'], label='Mexico', color='red')
plt.plot(global_prom['DATE'], global_prom['TD'], label='Promedio Global', linestyle='--', color='orange')
plt.xlabel('Fecha')
plt.ylabel('Muertes Totales (Log)')
plt.title('Comparacion de Muertes Totales: Mexico vs Global')
plt.legend()
plt.grid(True)


# Grafica 3: Indice de Rigurosidad (STI)
plt.figure(figsize=(10, 6))
plt.plot(mex['DATE'], mex['STI'], label='Mexico (STI)', color='green')
plt.xlabel('Fecha')
plt.ylabel('Indice de Rigurosidad')
plt.title('Evolucion de las Medidas de Control en Mexico')
plt.legend()
plt.grid(True)


# Estadistica descriptiva para el reporte
desc_stats = df.describe()
print(desc_stats)